### ISSUE TITLE
Please keep the attribution in my scripts

### ISSUE THREAD

**Issue by Hjdskes** [roberthluo/roberthluo.github.io#1]
Hey,

I see you've copied my scripts, which in itself is fine, but you removed the 

```
See https://hjdskes.github.io/blog/update-deploying-hugo-on-personal-github-pages/ for more information.
```

lines. Please add them back, so others are informed of 1) the origins of the script and 2) how they are intended to work.

**Comment by roberthluo** [comment]
Ok will do, didn't mean to do that on purpose!

**Comment by Hjdskes** [comment]
Thanks
